Facade Device for Drive Amplifier Device Class
synchrotron-solaris/dev-solaris-driveamplifier pull request #2
Opened 2017-07-28 13:13 UTC by stanislaw47

closes #1 
* added project structure, containing package, module and class for Drive Amplifier
* added documentation generated via `autodoc` and `apidoc`
* added `LICENSE`, updated `README` and `.gitignore`

About `proxy_commands`: `EnableTtl` and `DisableTtl`
as a decorator, `proxy_command` takes as second argument another command to execute. Thus, I've added argument `subcommand`. It looks strange, but as far as I'm concerned, it works fine.

2017-07-31 07:05 UTC, LJBD requested changes

2017-07-31 07:05 UTC, LJBD commented on drive_amplifier_ds/__init__.py
> +__author_email__ = "stanislaw.cabala@gmail.com"
Missing newline at the end of the file.

2017-07-31 07:05 UTC, LJBD commented on drive_amplifier_ds/drive_amplifier.py
> +                    "PSU status of the amplifier.")
It would be better to provide an unabbreviated alarms/statuses names. @wkitka - can you tell @stanislaw47 what do "VSWR" and "PSU" stand for?

2017-07-31 07:05 UTC, LJBD commented on drive_amplifier_ds/drive_amplifier.py
> +
You have some spaces left in the last line of the file. Please correct that to an empty last line.

2017-07-31 07:24 UTC, wkitka commented on drive_amplifier_ds/drive_amplifier.py
> +                    "PSU status of the amplifier.")
-  VSWR - Voltage Standing Wave Ratio,
- PSU - Power Supply Unit.

2017-08-03 09:22 UTC, LJBD approved these changes

2017-08-03 09:22 UTC, merged